use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Graph {
    pub id: Uuid,
    pub title: String,
    /// None for a root/top-level graph. Some(node_id) if this graph is a
    /// "zoom in" subgraph nested under a node in a parent graph.
    pub parent_node_id: Option<Uuid>,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Node {
    pub id: Uuid,
    pub graph_id: Uuid,
    pub title: String,
    pub description: String,
    pub status: MasteryStatus,
    /// IDs of nodes in the SAME graph that must be mastered first.
    pub prerequisite_ids: Vec<Uuid>,
    /// Set once a subgraph has been generated by zooming into this node.
    pub subgraph_id: Option<Uuid>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MasteryStatus {
    Unknown,
    Learning,
    Mastered { verified_at: DateTime<Utc> },
}
